

name: run python script

on: [push]

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run the Python script
        run: python python.py
